# Generated by Django 3.1.6 on 2021-02-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djuser',
            name='username',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
