# Generated by Django 3.1.6 on 2021-02-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djuser', '0002_auto_20210211_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djuser',
            options={'verbose_name': 'DJUSER', 'verbose_name_plural': 'DJUSER'},
        ),
        migrations.AddField(
            model_name='djuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자메일'),
            preserve_default=False,
        ),
    ]
